app:
  scheduler:
    enable: true
    interval: 10000
    force-check-delay: 10000

spring:
  application:
    name: scrapper

  liquibase:
    enabled: false

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

github:
  baseUrl: "https://api.github.com"

stackoverflow:
  baseUrl: "https://api.stackexchange.com/2.3"

bot:
  baseUrl: "http://localhost:8090"

db:
  username: "postgres"
  password: "postgres"
  baseUrl: "jdbc:postgresql://localhost:5432/scrapper"

springdoc:
  swagger-ui:
    path: /swagger.ui
